time-loop/clickup-projen

README.md
=> chore: update README.md with some guidance about what this does

src/clickup-cdk.ts
=> fix: bump minNodeVersion to work with eslint

README.md, src/clickup-cdk.ts
- minor README addition
- also add cdk-constants and cdk-iam-floyd to base deps
- fix node version in workflows
Fixes #
=> fix: increase workflowNodeVersion to match minNodeVersion

README.md, src/clickup-cdk.ts
- minor README addition
- also add cdk-constants and cdk-iam-floyd to base deps
- fix node version in workflows
- chore: update README.md example code
- fix: self-dependency
Fixes #
=> fix: need to also depend on clickup-projen

API.md, README.md, src/clickup-cdk.ts, src/clickup-ts.ts, src/codecov.ts, src/index.ts, test/clickup-ts.test.ts, test/codecov.test.ts
- chore: refactor to split out TypeScript stuff
- feat: add ClickUpTypeScriptProject library support
Fixes #
=> feat: add ClickUpTypeScriptProject

API.md, README.md, src/clickup-ts.ts, test/clickup-ts.test.ts
I also updated the bootstrapping instructions. Makes more sense now.
=> fix: instead of erroring, fix the prefix

README.md
=> chore: readme additions

.projen/tasks.json, package.json, yarn.lock
=> chore: upgrade dependencies

README.md, src/clickup-ts.ts
=> chore: make docs more generic

src/clickup-cdk.ts, src/clickup-ts.ts
=> fix: ClickUpTypeScriptProject should include @time-loop/clickup-projen as dep

README.md
=> chore: better docs around bootstrapping for new users

README.md, src/clickup-cdk.ts
and update the README to remove the no-longer necessary workarounds
Fixes #
=> fix: bugfix sample-code test snaphot

src/clickup-cdk.ts
override inherited `releaseToNpm`.
=> fix: do not releaseToNpm, it won't work and is also not useful

README.md
=> chore: README updates around bot user

src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
- refactor: extract defaults from super call
- feat: do not collect coverage for main.ts
Fixes #
=> feat: ignore main.ts for code coverage

README.md
Fixes #
* Should be executing the script and not putting script into .npmrc
=> fix: Clarify generating .npmrc step for PAT

README.md
=> chore: talk about ft_engineering

API.md, src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
That was just a bad idea. We shouldn't show people how to do that.
Fixes #
=> fix: remove snapshot testing example

README.md, src/clickup-cdk.ts, src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/clickup-ts.test.ts
=> fix: cdk constructs need to follow GitHub naming convention, too

README.md, src/clickup-cdk.ts
=> fix: repositoryUrl default

src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
=> fix: remove references to deprecated colors library from sample code

src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
=> feat: remove chalk and cdk-iam-floyd default deps

README.md, src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
Fixes import error when projen is used to create a cdk-app.
=> fix: remove cdk-iam-floyd from sample code

src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
=> fix: use Template.resourceCountIs instead of deprecated method

README.md
Make the titles easier for people to parse
Fixes #
=> chore: slightly better titles

src/clickup-ts.ts, src/codecov.ts, test/__snapshots__/clickup-ts.test.ts.snap, test/__snapshots__/codecov.test.ts.snap
=> fix: FORCE_PREBUILD_LAMBDA by default

API.md, src/clickup-cdk.ts, test/clickup-cdk.test.ts
=> feat(infra): Enable DD release event sending by default [CLK-179987]

README.md, triggerUpgradeMain.sh
=> feat(infra): Add easy dependency upgrade script for ops use [CLK-180642]

src/clickup-cdk.ts
Add `Dev` as an option of list of envs being deployed to in the PR template, since we will also be using `usInfraDev` env for shard envs.
=> feat(pr template): add Dev env checklist option in PR template [INFRA-530]

.gitignore, .projenrc.ts
Adds `.idea` to gitignore so I don't accidentally commit this
=> chore(gitignore): add .idea to .gitignore

README.md
Fixes #
Just updating readme with some instructions.
=> chore(hierarchy): Add some context json details

README.md
- cleanup lint
- chore(doc): some more cleanups
=> chore(doc): clarify cdk.context.json bootstrapping

renovate.json5, src/renovate-workflow.ts, test/renovate-workflow.test.ts
- Tested PR #126 
**Related task**: [CLK-228826](https://staging.clickup.com/t/333/CLK-228826)
Testing & Documentation
Renovate [docs](https://docs.renovatebot.com/configuration-options/#addlabels)
=> feat(infra): adding labels in renovate configuration [CLK-228826]

.github/workflows/add-to-project.yml, .github/workflows/renovate.yml, src/add-to-project.ts, src/renovate-workflow.ts, test/__snapshots__/add-to-project.test.ts.snap, test/__snapshots__/renovate-workflow.test.ts.snap
Updating GitHub Token in **renovate** workflows o use the new Organization secret 'RENOVATEBOT_GITHUB_TOKEN'
Related tasks:
- [CLK-230021](https://staging.clickup.com/t/333/CLK-230021)
- [CLK-228826](https://staging.clickup.com/t/333/CLK-228826)
=> feat(infra): updating GHToken in renovate workflows [CLK-230021]

src/clickup-cdk.ts
Fixes #
This PR fixes the issue with add-to-project workflow creation in other repos.
=> chore(infra): hot-fix for add-to-project

.github/CODEOWNERS
=> chore(settings): update CODEOWNERS [CLK-241027]

docs/cdk-diff/README.md
=> chore(core-services): Fix cdk-diff docs

src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
This reverts commit eb3059c269711c11887e14e5d40742a44b4571b1.
=> fix(cdk-app): revert jsii5 for cdk apps, too [CLK-250941]

src/clickup-cdk.ts, test/clickup-cdk.test.ts
=> feat(ClickUpCdkTypeScriptApp): pnpm throws [CLK-252116]

.projen/deps.json, .projenrc.ts, package.json, renovate.json5, src/datadog.ts, yarn.lock
=> chore(deps): upgrade JSII to v5.0.0 [CLK-255192]

API.md, README.md
Add reference to tagging requirements within what's left for you to do section of doc.
=> chore(security): add AWS Resource Tagging requirements [CLK-271835]

.github/workflows/renovate.yml, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
Update renovate to a newer version that uses ghcr.io for better performance and less ratelimiting
=> feat(renovate): update renovate action [CLK-272400]

docs/cdk-context-json/README.md
Fixes #
This PR updates the README outlining the context lookup workflow default behaviour.
=> chore(docs): README update outlining  context lookup workflow behaviour[CLK-323100]

renovate.json5, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
=> fix(infra): Bypass Prerelease Versions from Renovate PRs

src/datadog-service-catalog.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/datadog-service-catalog.test.ts.snap
- Fix alignment
- Removing unavailable property
=> chore(devops): fixing datadog provider schema message [CLK-346825] 

.github/workflows/renovate.yml, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
https://github.com/renovatebot/github-action/releases/tag/v40.0.0
=> chore(workflows): update renovate version to use node20 [INFRA-14946]

API.md, src/cdk-diff-workflow.ts
=> fix(cdk-diff): should work with pnpm [CLK-252116]

src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
This reverts commit 52062e39a94f187eb0e62db9c3a1ad8937baa5f1.
=> fix(ts): revert dist copy [CLK-252116]
