README.md
This PR updates initial repo setup to use `npx projen` in case people don't have public projen set up.
=> fix: Use `npx` to run projen for the first time

src/clickup-cdk.ts, src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
This is my attempt to solve the problem.
But unfortunately it does not: despite myapp-cdk/.projen/deps.json file generated has ts-node v10, the consequent run of `cd myapp-cdk && yarn projen` erases it back to v9. The only bullet-proof way to solve is to add `project.package.addDevDeps('ts-node@^10');` to myapp-cdk/.projenrc.js as you mentioned in Slack, but I can't find a way to modify the generated myapp-cdk/.projenrc.js file from inside clickup-cdk.ts.
**Test plan**
```
(cd clickup-projen && yarn build) && \
(rm -rf myapp-cdk; mkdir myapp-cdk; cd myapp-cdk; \
projen new --from ~/git/clickup-projen/dist/js/clickup-projen@0.0.0.jsii.tgz clickupcdk_clickupcdktypescriptapp)
```
=> fix: upgrade ts-node to tix resolveTypeReferenceDirective issue

README.md
Using the URL in the SAML error output doesn't work, so need to reauth with gh
=> chore: document gh cli re-auth

src/clickup-ts.ts
Adds `.idea` to gitignore for webstorm users. Otherwise I'm gonna end up checking this in by accident:
=> fix: add .idea to gitignore

.eslintrc.json, .github/workflows/pull-request-lint.yml, .github/workflows/release.yml, .projen/deps.json, .projen/tasks.json, .projenrc.ts, package.json, src/datadog.ts, test/__snapshots__/datadog.test.ts.snap, tsconfig.dev.json, yarn.lock
Task: https://staging.clickup.com/t/333/INFRA-256
Fixes #60 
- chore: Convert `.projenrc.js` to `.projenrc.ts` so we can import TS modules into the project AND reveal problems with the configuration itself
- fix: Correct the placement of invalid key `semanticTitleOptions` to start actually enforcing scope requirement
- fix: DD release event job must depend on release job for the build artifact...cannot run in parallel
=> fix(eng-prod): DD Release Event Job Must Depend On release Job [INFRA-256]

.projen/deps.json, .projenrc.ts, package.json, src/datadog.ts, test/__snapshots__/datadog.test.ts.snap, yarn.lock
Fixes #64 
- fix: JSON was previously being passed into the `event_tags` input, but this is invalid because of the double quotes. Instead, we need to pass in CSON which uses single quotes. Note their [Event Tags section](https://github.com/Glennmen/datadog-event-action#event-tags), which is not valid JSON.
Tested via `act`, screenshot below:
=> fix(eng-prod): CSON is used for the event_tags, not JSON [INFRA-53]

README.md
Most backend engineers have their Node version set to 12 since that is what we use on ECS/beanstalks. The projen setup will not work with Node 12 so I am adding a reminder to do `nvm use --lts` before using projen.
=> chore(core-services): update readme

src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
I've seen a number of repos which are adding `clickup-projen` as a devDep. So...
=> fix(devops): add self as devDep

src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
`@time-loop/clickup-projen` is also listed in dependencies which causes renovate to create 2 separate PRs to upgrade it. Packages only need to be listed in dependencies or dev dependencies and not both, so we remove it from dev dependencies  (removing it from dependencies may break things)
=> fix(dependencies): remove @time-loop/clickup-projen from dev dependencies

.projenrc.ts, API.md, renovate.json5, src/clickup-ts.ts
The renovate dashboard isn't listing the ecs fargate dependency due to the default behaviour of renovate to only update packages which don't match the semver range in the package.json:
> For example, if your package.json specifies a value for left-pad of ^1.0.0 and the latest version on npmjs is 1.2.0, then Renovate won't change anything because 1.2.0 satisfies the range. If instead you'd prefer to be updated to ^1.2.0 in cases like this, then configure rangeStrategy to bump in your Renovate config.
So we fix this by setting the `rangeStrategy` to `bump` to get the behaviour we want which most closely mimics projen's default package upgrade behaviour and will allow us not to waste time making manual update PRs
=> fix(renovate): set renovate range strategy to bump

.projenrc.ts, renovate.json5, src/clickup-ts.ts
Take 2 at fixing upgrading all deps by removing the `:preserveSemverRanges` preset.
=> fix(renovate): disable version pinning renovate preset

.projenrc.ts, renovate.json5, src/clickup-ts.ts
Prevents renovate trying to update the node version in the package.json as this is handled by projen:
=> fix(renovate): ignore node from renovate updates

README.md, triggerRenovate.sh
Fixes upgrade main script after the move to renovate. Tested and it works great:
```
mattlewis@Matts-MacBook-Pro-2 clickup-projen % REPO_SUFFIX='stage1-cdk' ./triggerRenovate.sh
Verified gh CLI tool is accessible.
Triggering renovate workflow on repo stage1-cdk
✓ Created workflow_dispatch event for renovate.yml at main
To see runs for this workflow, try: gh run list --workflow=renovate.yml
Verifying workflow_dispatch event was actually created...
Trigger succeeded. Continuing...
Total failure count is: 0
```
Triggered:
=> chore(renovate): rename and fix upgrade trigger script

src/datadog.ts, test/__snapshots__/datadog.test.ts.snap
On 1st June this will break the world: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix(datadog): migrate away from deprecated github action syntax for setting outputs

.github/workflows/renovate.yml, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
Solves this problem by running renovate when the rebase checkbox is ticked on a pull request:
=> fix(renovate): run renovate when a user ticks the rebase now option on a PR

.projenrc.ts, renovate.json5, src/clickup-ts.ts, src/renovate-workflow.ts, test/renovate-workflow.test.ts
1. Refactors renovate config so it's shared in 1 place to make it easier to make updates while still letting us override defaults on a per usage basis if required
2. Fixes this rate limit problem caused by renovate only creating a maximum of 2 PRs per run 
3. Produce less weekly update PRs by grouping these dependency and dev dependency update PRs together:
=> fix(renovate): make sure all weekly renovate PRs are created + produce less PRs

src/cdk-diff-workflow.ts, test/__snapshots__/clickup-cdk.test.ts.snap
* Bump `@time-loop/cdk-log-parser` `0.0.0` -> `0.0.1`
* This new version has additional handling to filter out meaningless ssm diffs due to timestamp changes
* Example:
```
[~] Custom::AWS UsQaQaUsEast21/ServiceInstance/ServiceInstanceUserRemote/Resource ServiceInstanceUser
├─ [~] Create
│   ├─ [-] {"service":"SSM","action":"getParameter","parameters":{"Name":"/ClickUpEcs/Deploy/DeployUser/DeployUsQaUserArn"},"region":"us-east-1","physicalResourceId":{"id":"timestamp1676258561787"}}
│   └─ [+] {"service":"SSM","action":"getParameter","parameters":{"Name":"/ClickUpEcs/Deploy/DeployUser/DeployUsQaUserArn"},"region":"us-east-1","physicalResourceId":{"id":"timestamp1676295292450"}}
└─ [~] Update
├─ [-] {"service":"SSM","action":"getParameter","parameters":{"Name":"/ClickUpEcs/Deploy/DeployUser …
```
=> chore(inbox): Bump cdk-log-parser dep for cdk-diff workflow

src/cdk-diff-workflow.ts, test/__snapshots__/clickup-cdk.test.ts.snap
* Bumps `cdk-log-parser` dependency for `cdk-diff-workflow`
* Context: Some cdk-diff runs have extra output and this caused issues with the older log parser versions. This was resolved in `0.0.4`
* Example:
=> fix(inbox): Fix issue where stack name was getting clobbered

src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
This reverts commit 693fe66e0b7f8b52236f6199065ae3c37845f0f4.
cdkPipeline's runner were failing with
```
[1/5] Validating package.json...
error clickup-ecs-cdk@0.0.0: The engine "node" is incompatible with this module. Expected version ">= 14.21.3". Got "14.19.3"
```
=> chore(deps): REVERT bump min node version to 14.21.3

src/cdk-diff-workflow.ts, test/__snapshots__/clickup-cdk.test.ts.snap
* Each new version of this lib should be adopted automatically without having to update this repo.
* Loose pinned it to accomplish this!
* Tested this locally with `yalc` and performs as expected
=> chore(deps): Bump cdk-diff-log parser and loose pin it!

src/clickup-cdk.ts, src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
npm-check-updates dropped support for node 14 in a breaking change which [breaks some of our node 14 CDK pipelines](https://click-up.slack.com/archives/C03F94339PV/p1683585591180999)
Until that package fixes the issue, we need to add a resolution to the package.json to force the use of an older version that supports node 14
See https://github.com/raineorshine/npm-check-updates/issues/1300 for more info
=> fix(deps): pin npm-check-updates to last version that supported node 14

src/clickup-cdk.ts, src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
Reverts time-loop/clickup-projen#158
This is no longer needed! https://github.com/raineorshine/npm-check-updates/issues/1300#issuecomment-1540664025
=> fix(deps): unpin npm-check-updates now that node 14 support has been restored

src/clickup-ts.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap
This does some magic to allow the package read token to be available for deps and still use the Github token when doing a package write during the Release step
=> fix(cloud-platform): use env vars to our advantage [CLK-255341]

src/cdk-diff-workflow.ts, test/__snapshots__/cdk-diff-workflow.test.ts.snap, test/__snapshots__/clickup-cdk.test.ts.snap
* The output of `cdk ls -j` should be pure and have no extra output so it can be consumed by `jq`
* Unfortunately, cdk adds in notices when things are out of date
* Added the `--notices=false` flag to prevent the extra output from causing JSON parsing errors
* While the `env-no-changes` labels don't control the auto merging, they can be confusing to reviewers if there are both cdk diff comments and `env-no-changes` labels
* This happens when any commit has no changes, the labels get added
* Then a subsequent commit introduces changes but the labels never get removed
* Added a step per env to remove labels if present when a diff exists for that env
* Can see this in action below!
* Updated cdk-log-parser to always use the latest version to avoid needing to update this repo every time a …
=> fix(cloud-platform): suppress notices from cdk as they are invalid JSON

renovate.json5, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
Fixes #128 
https://click-up.slack.com/archives/C05RL91C490/p1694534858319609
=> fix(infra): Separate clickup-projen into different packageRule

src/clickup-ts.ts
**Related task**: [CLK-324594](https://staging.clickup.com/t/333/CLK-324594)
- Fixing the use of `typedoc-plugin-markdown`
The `typedoc.json` file required the plugin configuration section to allow the creation of the documentation using the `typedoc-plugin-markdown`
=> chore(devops): fixing use of typedoc-plugin-markdown plugin [CLK-324594]

docs/cdk-context-json/README.md, docs/cdk-diff/README.md
fixing typo in docs [CLK-346284]
Related task: [CLK-346284](https://staging.clickup.com/t/333/CLK-346284)
=> chore(docs): fixing typo in docs [CLK-346284]

src/datadog-service-catalog.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/datadog-service-catalog.test.ts.snap
fixing schema-version parameter for dd service catalog
**Related task** [CLK-346825](https://staging.clickup.com/t/333/CLK-346825)
**Related documentation** [here](https://github.com/marketplace/actions/datadog-service-catalog-metadata-provider#schema-fields)
=> chore(devops): fixing schema-version parameter for dd service catalog [CLK-346825]

src/clickup-cdk.ts, test/__snapshots__/clickup-cdk.test.ts.snap
Per https://github.com/mozilla/source-map/issues/454 "This is fixed in [source-map@0.7.4](https://www.npmjs.com/package/source-map/v/0.7.4)."
Symptom:
```
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
at readWasm (/home/runner/work/infratest-aurora-cdk/infratest-aurora-cdk/node_modules/v8-to-istanbul/node_modules/source-map/lib/read-wasm.js:8:13)
at wasm (/home/runner/work/infratest-aurora-cdk/infratest-aurora-cdk/node_modules/v8-to-istanbul/node_modules/source-map/lib/wasm.js:25:16)
at /home/runner/work/infratest-aurora-cdk/infratest-aurora-cdk/node_modules/v8-to-istanbul/node_modules/source-map/lib/source-map-consumer.js:264:14
at V8ToIstanbul.load …
```
=> feat(cdk): force source-map to ^0.7.4 [CLK-393642]

.github/workflows/release.yml, src/datadog-service-catalog.ts, src/datadog.ts, src/slack-alert.ts, test/__snapshots__/clickup-cdk.test.ts.snap, test/__snapshots__/clickup-ts.test.ts.snap, test/__snapshots__/datadog-service-catalog.test.ts.snap, test/__snapshots__/datadog.test.ts.snap, test/__snapshots__/slack-alert.test.ts.snap
Fixes failing workflows due to the artifact being uploaded with v4 and the download action still uses v3 (which uses different APIs and fails as a result)
=> fix(alerts): upgrade download-artifact action to v4 [CLK-483275]

src/cdk-diff-workflow.ts, test/__snapshots__/clickup-cdk.test.ts.snap
Removes `cdk-log-parser` module version so that each repo can manage the proper version for this module
=> feat(workflows): replace cdk-log-parser tag with semver notation [CLK-493280]

.github/workflows/semgrep.yml, src/semgrep-workflow.ts, test/__snapshots__/semgrep-workflow.test.ts.snap
Updating semgrep docker image to [1.78.0](https://hub.docker.com/layers/semgrep/semgrep/1.78.0/images/sha256-aeb24a8f042cb60fc64a87c6e52b01033fb11442fd224ccc41cc363f5ca3aa10?context=explore)
=> feat(security): update semgrep to 1.78.0 [SEC-8536]

src/cdk-diff-workflow.ts, test/__snapshots__/cdk-diff-workflow.test.ts.snap
Fixes #
- update GH artifact actions to v4
```typescript
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3.1.2`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
=> fix(cloud-platform): update GH artifact actions to v4[INFRA-31035]

renovate.json5, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
Tells renovate to ignore trying to update the pnpm version in the package.json as projen then just overrides it and we end up with renovate creating empty commits like so: https://github.com/time-loop/public-sharing-frontend-cdk/pull/121
=> fix(renovate): ignore pnpm from being upgraded by renovate [CLK-616357]

renovate.json5, src/renovate-workflow.ts, test/__snapshots__/renovate-workflow.test.ts.snap
Updates Renovate configuration to use current non-deprecated options:
- Replace 'config:base' with 'config:recommended' preset
- Replace 'github>whitesource/merge-confidence:beta' with 'mergeConfidence:all-badges'
- Replace matchPackagePatterns/excludePackagePatterns with matchPackageNames syntax
- Replace matchPackagePrefixes with matchPackageNames syntax
- Update comment references to reflect config:recommended usage
These deprecated options were causing "Config Migration Needed" warnings
that blocked Renovate from creating dependency update PRs in downstream
projects. This change aligns with Renovate's current configuration
schema and resolves the blocking migration issues.
Fixes dependency update blocking in field-service-cdk and other repos
using this configuration.
=> fix(renovate): update deprecated configuration options [INFRA-61273]
